title: Matt Hashemi
logo: /assets/img/headshot_circle_2.png
description: |
  Senior Staff Software Engineer<br>
  <strong>Location:</strong> San Francisco Bay Area<br>
  <strong>Phone:</strong> (415) 636-9653<br>
  <strong>Email:</strong> <a href="mailto:matt.hashemi.info@gmail.com">matt.hashemi.info@gmail.com</a><br>
  <strong>LinkedIn:</strong> <a href="https://linkedin.com/in/matt-hashemi/">linkedin.com/in/matt-hashemi</a>
show_downloads: true
theme: jekyll-theme-minimal
